name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta todos los días a la medianoche UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          user: zeika-coder
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, repositories
          config_timezone: America/Mexico_City
          plugin_calendar: yes
          plugin_calendar_limit: 1
